In [1]:
import pandas as pd
from pycaret.regression import *
insurance_df = pd.read_csv("insurance.csv")

In [2]:
insurance_df['sex'] = insurance_df['sex'].replace({'male': 'mężczyzna', 'female': 'kobieta'})

# Aktualizacja wartości w kolumnie `smoker`
insurance_df['smoker'] = insurance_df['smoker'].replace({'yes': 'tak', 'no': 'nie'})

# Aktualizacja wartości w kolumnie `region`
insurance_df['region'] = insurance_df['region'].replace({
    'southeast': 'południowy wschód',
    'southwest': 'południowy zachód',
    'northeast': 'północny wschód',
    'northwest': 'północny zachód',
    })

In [3]:
reg_setup = setup(
    data=insurance_df,
    target='charges',
    session_id=123,
    
    categorical_features=['sex', 'smoker', 'region']
)

In [4]:
model = create_model(estimator='lr')

In [5]:
best_model = compare_models()

In [6]:
evaluate_model(best_model)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [7]:
save_model(best_model, 'best_insurance_model')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(include=['age', 'bmi', 'children'],
                                     transformer=SimpleImputer())),
                 ('categorical_imputer',
                  TransformerWrapper(include=['sex', 'smoker', 'region'],
                                     transformer=SimpleImputer(strategy='most_frequent'))),
                 ('ordinal_encoding',
                  TransformerWrapper(include=['sex', 'smoker'],
                                     transfor...
                                                                          'data_type': dtype('O'),
                                                                          'mapping': kobieta      0
 mężczyzna    1
 NaN         -1
 dtype: int64},
                                                                         {'col': 'smoker',
                                                                          'data_type': dtype('O'),
                                                                          'mapping': nie    0
 tak    1
 NaN   -1
 dtype: int64}]))),
                 ('onehot_encoding',
                  TransformerWrapper(include=['region'],
                                     transformer=OneHotEncoder(cols=['region'],
                                                               handle_missing='return_nan',
                                                               use_cat_names=True))),
                 ('trained_model', GradientBoostingRegressor(random_state=123))]),
 'best_insurance_model.pkl')